#Twitter Sentiment Analysis for Beginners.ipynb  Automatically generated by Colaboratory Original file is located at https://github.com/nikitasilaparasetty/Twitter-Sentiment-Analysis-Projects-2022-/blob/master/Twitter%20Sentiment%20Analysis%20for%20Beginners.ipynb
#pip install tweepy textblob wordcloud better_profanity
import re 
import numpy as np
import tweepy 
from tweepy import OAuthHandler 
from textblob import TextBlob 
import matplotlib.pyplot as plt
import pandas as pd
from wordcloud import WordCloud
from better_profanity import profanity
#https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-encrypted-secrets-for-your-repository-and-organization-for-github-codespaces#adding-secrets-for-a-repository
import os
consumer_key = os.getenv('API_KEY')
#consumer_key = {{ tweetauth.API_KEY }}
consumer_secret = os.getenv('API_KEY_SECRET')
bearer_token = os.getenv('BEARER_TOKEN')
access_token = os.getenv('ACCESS_TOKEN')
access_token_secret = os.getenv('ACCESS_TOKEN_SECRET')
consumer_key=consumer_key.strip()
consumer_secret=consumer_secret.strip()
bearer_token=bearer_token.strip()
access_token=access_token.strip()
access_token_secret=access_token_secret.strip()
print(consumer_key,consumer_secret,bearer_token,access_token,access_token_secret)
# Authenticate to Twitter
auth = tweepy.OAuthHandler(consumer_key,consumer_secret)
auth.set_access_token(access_token,access_token_secret)
api = tweepy.API(auth)
print(api)
#media = api.media_upload(filename="./cloud.png")
#print("MEDIA: ", media)
#tweet = api.update_status(status="dis-ease wordcloud", media_ids= [media.media_id_string])
#print("TWEET: ", tweet)
status = "Twitter using the API"
api.update_status(status=status)
