# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: app
  env: |
    API_KEY: ${{ secrets.API_KEY }}
    API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
    BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

on: 
  schedule:
    - cron: "15 * * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    environment: tweetauth

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy matplotlib pandas textblob wordcloud better_profanity 
    - name: master
      run: |
        python twitter_sentiment_analysis_for_beginners.py
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        git add --all
        git commit -am "add data"
        git push
